# Generated by Django 3.0.7 on 2020-06-05 05:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confusion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='confused_students',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='room',
            name='total_students',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.DeleteModel(
            name='Confusion',
        ),
    ]
