# Generated by Django 3.0.7 on 2020-06-10 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confusion', '0002_auto_20200605_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='student_slug',
            field=models.SlugField(default='default-slug', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='teacher_slug',
            field=models.SlugField(default='default-slug', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.TextField(),
        ),
    ]
