# Generated by Django 3.0.7 on 2020-06-10 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confusion', '0005_remove_room_total_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='confused_students',
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='action',
            field=models.IntegerField(choices=[(1, 'Plus One'), (-1, 'Minus One')]),
        ),
        migrations.AlterField(
            model_name='confusionrecord',
            name='action',
            field=models.IntegerField(choices=[(1, 'Plus One'), (-1, 'Minus One')]),
        ),
    ]
